# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx

julia:
  - 1.2
  - nightly

matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
 
notifications:
  email: false

addons:
  apt:
    packages:
    - xorg-dev
    
before_script:
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then 
      export DISPLAY=:99.0
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x32
      sleep 3
    fi
  
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
  
# jobs:
#  include:
#    - stage: Documentation
#      julia: 1.1
#      script: julia --project=docs -e '
#          using Pkg;
#          Pkg.develop(PackageSpec(path=pwd()));
#          Pkg.instantiate();
#          include("docs/make.jl");'
#      after_success: skip
